title: <p align="center"> Neelima Guntupalli </p>

logo: "/images/profile_pic_new.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/neelimag/">LinkedIn</a> |
  <a href="https://github.com/neel-machine">GitHub</a>
  </p>
  
  <p align="center">
  <i>"The best way to learn anything is to do the thing"</i>
  </p>
  
  <p align="center">
  I am currently pursing MS degree in ML/AI at Liverpool John Moores University
  and working as a part-time Intern at B-STEM with a focus on ML/AI.
  </p>
  <br><br>
  
  <a href="https://neel-machine.github.io/project_portfolio#NLP">NLP Projects</a>
    <br><br>

  <a href="https://neel-machine.github.io/project_portfolio#MLProj">Machine Learning Projects</a>
    <br><br>

  <a href="https://neel-machine.github.io/project_portfolio#Micro">Micro Projects</a>

  </p>
  
theme: jekyll-theme-minimal
