title: <p align="center"> Neelima Guntupalli </p>

logo: "/images/profile_pic.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/neelimag/">LinkedIn</a> |
  <a href="https://github.com/neel-machine">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in ML/AI at Liverpool John Moores University.
  I am currently looking for internships in this field.
  <br><br>
  <a href="https://github.com/neel-machine/project_portfolio/blob/main/index.md#telecom-churn-case-study">Scroll</a>

  </p>
  
theme: jekyll-theme-minimal
